version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: biblioteca_test
      POSTGRES_USER: bibliotecaAdmin
      POSTGRES_PASSWORD: a.123456
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
